spring:
  application:
    name: audition-api
  config:
    import: "optional:configserver:"
  main:
    allow-bean-definition-overriding: true
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
  mvc:
    throw-exception-if-no-handler-found: true

server:
  max-http-request-header-size: 16KB
management:
  tracing:
    sampling:
      probability: 1.0
  endpoints:
    web:
      exposure:
        include: 'info,health' # Secured: Only expose info and health
logging:
  pattern:
    level: "%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]"